replicaCount: 3

image:
  tag: main

service:
  type: NodePort
  port: 8082  # 修改为 8082

env:
  NODE_ENV: production
  APP_VERSION: "1.0.0-prod"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
