replicaCount: 1

image:
  tag: main

service:
  type: NodePort
  port: 8080  # 修改为 8080

env:
  NODE_ENV: development
  APP_VERSION: "1.0.0-dev"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
